### ISSUE TITLE
Does this work? 

### ISSUE THREAD

**Issue by HadiElKarhani** [carlos-menezes/fc-clubs-api#1]
Hi, sorry I am leaving a message here @carlos-menezes , but I couldn't find another way to contact you. Just wanted to ask you if this still works on FC 24?

Thank you in advance for your answer!

**Comment by carlos-menezes** [comment]
Hey! It has been a while since I've used (and done any maintenance on) this API. Are the tests not passing?

**Comment by HadiElKarhani** [comment]
Thanks for your response @carlos-menezes ! Not all are passing unfortunately, I am getting some json data from some requests but not all. Is there a documentation that you followed when building this? I am not finding any that are provided by EA xD

Maybe I can help out!

**Comment by carlos-menezes** [comment]
Thanks for raising the issue! 😄 

I just created a wrapper for the requests made here: https://www.ea.com/en-gb/games/ea-sports-fc/clubs/rankings

They might have changed some of the endpoints or the any of the schemas.

**Comment by HadiElKarhani** [comment]
I see, thanks for sharing! And from your previous experience on this, is there any endpoint to get match/player statistics from friendly matches in pro clubs?

**Comment by carlos-menezes** [comment]
I'm not exactly sure there's an endpoint for retrieving stats from friendly games (only playoffs and league matches, which are documented in the README). If you play a friendly match and tell me the name of your club, I could possibly dig into the network tab and see if there's an endpoint for that.

**Comment by HadiElKarhani** [comment]
We only play friendlies almost every night with a club named "BINGUS ESPORTS"

I would love to know if friendlies stats retrieval is possible.

**Comment by carlos-menezes** [comment]
https://www.ea.com/en-gb/games/ea-sports-fc/clubs/match-history?clubId=7875460&platform=common-gen5

I assume you cannot see any of these matches here, can you?

**Comment by HadiElKarhani** [comment]
Correct, none of the matches here are friendlies.

**Comment by mubarakshow** [comment]
@carlos-menezes thanks for this amazing work! ❤️ 
Just ran the tests and they all passed ✅ 

![Screenshot 2024-07-02 at 08 23 53](https://github.com/carlos-menezes/fc-clubs-api/assets/42121149/d8197fa8-1899-4141-a38b-b6e36a822c8a)

**Comment by carlos-menezes** [comment]
@mubarakshow happy to help.
